# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.8'

gem 'puma', '3.12.1'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.0'
# Use Redis adapter to run Action Cable in production
gem 'mock_redis', '0.19.0'
gem 'rails-healthcheck', '1.0.3'
gem 'redis', '4.1.2'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

gem 'uuid', '~> 2.3', '>= 2.3.8'

gem 'service-base', path: '../gems/service-base'
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', '11.0.1', platforms: %i[mri mingw x64_mingw]
  gem 'rubocop', '~> 0.74.0', require: false
  gem 'rubocop-rails', require: false
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring', '2.0.2'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem 'rspec-rails', '3.7.2'
  gem 'shoulda-matchers', '4.3.0'
end

gem 'sprockets', '3.7.2'

gem 'geocoder', '~> 1.3.7'
gem 'rest-client', '2.0.2'
gem 'simplecov', '0.15.1', require: false, group: :test
gem 'will_paginate', '3.1.6'
