# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/buster64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
    # Customize the amount of memory on the VM:
    vb.memory = "512"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get install -y aptitude python python-setuptools python3 python3-setuptools
  SHELL

  # Allows us to use a single key for all machines located at ~/.vagrant.d/insecure_private_key
  # Since we are using this setup for local tests only, there are no security concerns about using that key
  config.ssh.insert_key = false

  # Configure multiple machines
  # More at: https://www.vagrantup.com/docs/multi-machine/
  config.vm.define "big-machine-1" do |big_machine_1|
    big_machine_1.vm.network "private_network", ip: "10.10.10.100"

    big_machine_1.vm.provider "virtualbox" do |vb|
      vb.name = "big-machine-1"
    end
  end

  config.vm.define "big-machine-2" do |big_machine_2|
    big_machine_2.vm.network "private_network", ip: "10.10.10.101"

    big_machine_2.vm.provider "virtualbox" do |vb|
      vb.name = "big-machine-2"
    end
  end

  config.vm.define "small-machine-1" do |small_machine_1|
    small_machine_1.vm.network "private_network", ip: "10.10.10.102"

    small_machine_1.vm.provider "virtualbox" do |vb|
      vb.name = "small-machine-1"
    end
  end

  config.vm.define "small-machine-2" do |small_machine_2|
    small_machine_2.vm.network "private_network", ip: "10.10.10.103"

    small_machine_2.vm.provider "virtualbox" do |vb|
      vb.name = "small-machine-2"
    end
  end

  config.vm.define "gateway-machine" do |gateway_machine|
    gateway_machine.vm.network "private_network", ip: "10.10.10.104"

    gateway_machine.vm.provider "virtualbox" do |vb|
      vb.name = "gateway-machine"
    end
  end
end
