# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.8'

gem 'httparty', '~> 0.14.0'
gem 'kong', '~> 0.3'
gem 'rails-healthcheck', '1.0.3'
gem 'spring', '2.0.0', group: :development
gem 'sqlite3', '1.4.1'

# Sidekiq and redis
gem 'redis', '4.1.2'
gem 'redis-namespace', '1.6.0'
gem 'sidekiq', '5.2.7'

gem 'colorize', '0.8.1'

gem 'service-base', path: '../gems/service-base'

group :development, :test do
  gem 'rspec-rails', '~> 3.8.0'
  gem 'rubocop', '~> 0.74.0', require: false
  gem 'rubocop-rails', require: false
end

gem 'simplecov', '0.12.0', require: false, group: :test

gem 'sprockets', '~> 3.0'

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
