---
- name: Install python dependencies
  apt:
    pkg:
      - python3-jsondiff
      - python3-yaml
- name: Set data path
  set_fact:
    swarm_deployments_data_path: "{{ swarm_deployments_path }}/data"
- name: Create stacks diretory
  file:
    state: directory
    path: "{{ swarm_deployments_path }}/stacks/"
- name: Copy stacks to the manager
  template:
    src: interscity-platform.yml.j2
    dest: "{{ swarm_deployments_path }}/stacks/interscity-platform.yml"
- docker_stack:
    state: present
    name: interscity-platform
    compose:
      - "{{ swarm_deployments_path }}/stacks/interscity-platform.yml"
  retries: 5
  delay: 10
- name: Check services
  uri:
    url: "http://{{ kong }}:{{ kong_port }}/{{ item }}/healthcheck"
  failed_when: false
  register: _check
  until: _check['status'] == 200
  retries: 360
  delay: 10
  loop:
    - actuator
    - adaptor
    - catalog
    - collector
    - discovery
  ignore_errors: "{{ ansible_check_mode }}"
- name: Success
  vars:
    message: |
      The deploy was successful.
      You can find the InterSCity services at:
        - Actuator: http://{{ ansible_host }}:{{ kong_port }}/actuator
        - Adaptor: http://{{ ansible_host }}:{{ kong_port }}/adaptor
        - Catalog: http://{{ ansible_host }}:{{ kong_port }}/catalog
        - Collector: http://{{ ansible_host }}:{{ kong_port }}/collector
        - Discovery: http://{{ ansible_host }}:{{ kong_port }}/discovery
  debug:
    msg: "{{ message.split('\n') }}"
